version: "3.7"

services:
  # Backend API
  backend-api:
    container_name: backend
    # image: node:12.2.0
    build: ./
    command: npm start
    working_dir: /usr/src/schooldash/server
    environment:
      POSTGRES_URI: postgres://aj:secret@postgres:5432/dashr-dock
      REDIS_URI: redis://redis:6379
      # use links to connect to outside services
    ports:
      - "5001:5001"
      # maps HERE to: THERE
    volumes:
      - ./:/usr/src/schooldash/server
      # Postgres
  postgres:
    environment:
      POSTGRES_USER: aj
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dashr-dock
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
